export const mock = {
  sidebar: [
    {
      id: "AYSI32392",
      user: "https://tse2.mm.bing.net/th?id=OIP.cJwC51YhZRRSndTONMPxQAHaHa&pid=Api&P=0&h=180",
      name: "Danielle Munchen",
      lastName: "Schollengberg",
      status: "Active",
      student: [
        {
          period: "2023-1",
          name: "Sobre el estudiante",
          status: "Alumno Regular",
          school: "Adebaran",
          admission: "Centro pre",
          segment: "Sin informacion",
          quimica: "Riesgo sin difinir (nota sin información)",
          matematica: "Riesgo sin difinir (nota sin información)",
          programacion: "Riesgo sin difinir (nota sin información)",
          comunicacion: "Riesgo sin difinir (nota sin información)",
        },
      ],
      about: [
        {
          name: "About",
          firstName: "Danielle",
          lastName: "Munchen Schollengber",
          email: "danielle_munchen@gmail.com",
          editEmail: "mdi-pencil",
          phoneNumber: "+54 3453443432",
          country: "México",
          category: "Do not Contract",
        },
      ],
      career: [
        {
          name: "Career name",
          careerId: "03938P",
          type: "Gradute",
          modality: "On-Campus",
          status: "Enrollment",
          studentId: "AYSI012343",
          cohort: "A1 2023",
        },
      ],
    },
  ],
  cardOverview: [
    {
      icon: "today",
      age: "Record Age",
      days: "12 days",
      created: "Created on",
      createDate: "Jan 2, 2023",
    },
    {
      icon: "check_circle",
      conf: "mdi-cog",
      age: "Status",
      days: "Active",
      created: "Update",
      createDate: "Jan 2, 2023",
    },
    {
      icon: "location_on",
      age: "Country",
      days: "México",
      created: "State",
      createDate: "Cordoba",
    },
    {
      icon: "contact_page",
      age: "Last contact",
      days: "2 days ago",
      created: "Nov 29, 2023",
      createDate: "2:43pm",
    },
    {
      icon: "timeline",
      age: "Last activity",
      days: "7 days ago",
      created: "Nov 29, 2023",
      createDate: "2:43pm",
    },
  ],
};
